# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-builder" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "6bf030a2c9dbc80a8062748be2829ce56f1492ab5a7a187abb3aca9df655d233"
      url "https://github.com/martinsuchenak/agent-builder/releases/download/v#{version}/agent-builder_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbf15b38212a8fb9847cea094a8e4aa8ada238feca8f0a9298f013e1c62753d5"
      url "https://github.com/martinsuchenak/agent-builder/releases/download/v#{version}/agent-builder_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c597583dc4fbb6a3c44522882938ba8f561c5550e7db2b6cee0f9a00931cc73f"
      url "https://github.com/martinsuchenak/agent-builder/releases/download/v#{version}/agent-builder_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2382ca4902b4b4720c16f79206248f469c8e304c676e1a777feec6c3cea0ef27"
      url "https://github.com/martinsuchenak/agent-builder/releases/download/v#{version}/agent-builder_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agent-builder"
  desc "Compile canonical AI-agent artifacts into platform-specific formats"
  homepage "https://github.com/martinsuchenak/agent-builder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-builder"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-builder"]
    end
  end

  # No zap stanza required

end
