# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-scaffolder" do
  version "0.0.11"

  on_macos do
    on_intel do
      sha256 "07d0164bb727e22b9da67abc05132ac87926e05cfa75b9d7ad6d7e6d1eeca79b"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "248f8416ef28a2fe471d48f079b56a08891bed34b0de4672eda88143333fbbc6"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7adc3c44a9ebd7e7eac2dbadfa2dcfd425c1272a39eaeef53f7c9924f9c786f7"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "79a83af2913b9cca99b8d359a98ec413a199ba48f8bf80786dea567371857059"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-scaffolder"
  desc "Scaffold fully functional Go microservice projects"
  homepage "https://github.com/martinsuchenak/go-scaffolder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-scaffolder"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-scaffolder"]
    end
  end

  # No zap stanza required

end
