# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-scaffolder" do
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_darwin_amd64.tar.gz"
      sha256 "ce83977304632eb46a41f9bb92466557d98cbb91fc70a0a06b2d243c3012a5eb"
    end
    on_arm do
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_darwin_arm64.tar.gz"
      sha256 "456746f5e4e022735a97a8de29cbd4e6408e77c23e4f0e72e66064c2b840b63d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_linux_amd64.tar.gz"
      sha256 "1ce3a94e4a4782deaec142b1d75c9b2311b6ee625a757863044a4acd4ad6d62f"
    end
    on_arm do
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_linux_arm64.tar.gz"
      sha256 "22e71a8f4cfac2b294cd72d56ddace9ed426f0dcf2b1670723287d450fce4704"
    end
  end

  name "go-scaffolder"
  desc "Scaffold fully functional Go microservice projects"
  homepage "https://github.com/martinsuchenak/go-scaffolder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-scaffolder"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-scaffolder"]
    end
  end

  # No zap stanza required

end
