# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-scaffolder" do
  version "0.0.10"

  on_macos do
    on_intel do
      sha256 "c2f09360854a970caf8d4ad31735c9407819b8ed95289c33de3e3c8bda6d6998"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7c0ef707d09978c328910938caaf22749bec8df28bfabd3c1aeb6d9fe62e3f4"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7b3ecfec2acd04e93bc1bb295cc8bfe66f0a7bfd12f99b07ac9da62094845e1"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2067172a4a6428b9eca44d3cf762a0cbaf9164d6c75e62edf6bc2afb726e37c"
      url "https://github.com/martinsuchenak/go-scaffolder/releases/download/v#{version}/go-scaffolder_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-scaffolder"
  desc "Scaffold fully functional Go microservice projects"
  homepage "https://github.com/martinsuchenak/go-scaffolder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-scaffolder"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-scaffolder"]
    end
  end

  # No zap stanza required

end
