# This file was generated by GoReleaser. DO NOT EDIT.
cask "phantom" do
  name "phantom"
  desc "CLI tool for managing overlay filesystems for parallel AI agent development"
  homepage "https://github.com/martinsuchenak/phantom"
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phantom"

  on_macos do
    on_intel do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_darwin_amd64.tar.gz"
      sha256 "31b0ab5589d5d48ef475183b2115e0b09162126029124e22cae14c9f7a127b69"
    end
    on_arm do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_darwin_arm64.tar.gz"
      sha256 "f59959b1a41c28142aab23c8ee03f15af3bfcb226af93cc64befa35a46ef1de9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_linux_amd64.tar.gz"
      sha256 "6068fae697de72daa9aa42d21a3d22224cdba026bdea05f1e73d7ab912506e2d"
    end
    on_arm do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_linux_arm64.tar.gz"
      sha256 "ec14222efceb5a4175b760cbf49418ce6c553c7cd5e3d33b07224c672fcdf250"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phantom"]
    end
  end

  # No zap stanza required
end
