# This file was generated by GoReleaser. DO NOT EDIT.
cask "phantom" do
  version "0.0.18"

  on_macos do
    on_arm do
      sha256 "0e3ff172e7761ebd2238ea27e151a504ec5c47e393d9fca2267fb774076917d5"
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "86e22519775f3e0c99e04f9ef0b40b8156319f3e3e1a8b04eb32767d081f6613"
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "00b6e4fd86d9af13482b46e2547070ef9e2b5b7df04dc3abf258fa648aaaad85"
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c0129777a27630242cc9a452c23c98e3b07604a124e087b6b0a45759b250a95"
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "phantom"
  desc "CLI tool for managing overlay filesystems for parallel AI agent development"
  homepage "https://github.com/martinsuchenak/phantom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phantom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phantom"]
    end
  end

  # No zap stanza required
end
