# This file was generated by GoReleaser. DO NOT EDIT.
cask "phantom" do
  name "phantom"
  desc "CLI tool for managing overlay filesystems for parallel AI agent development"
  homepage "https://github.com/martinsuchenak/phantom"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phantom"

  on_macos do
    on_intel do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_darwin_amd64.tar.gz"
      sha256 "b1ccf15aaa06f60c0d8970ec4e5502360cb39c0742a7f0eeb72a2b0b0a3e9876"
    end
    on_arm do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_darwin_arm64.tar.gz"
      sha256 "69f2d021b302c042a53934dfb73e55e9050ae4faee0eb9b2b527d16690caa54b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_linux_amd64.tar.gz"
      sha256 "292db5453fe56a812c83a651715e2cef171758e568efc5ea7932f97fd1c5d199"
    end
    on_arm do
      url "https://github.com/martinsuchenak/phantom/releases/download/v#{version}/phantom_#{version}_linux_arm64.tar.gz"
      sha256 "cbee2c188c2ac1d585e38c4f8e2b7c983f718ed5eb5fd8aedd8584aed07d1614"
    end
  end

  # No zap stanza required
end
