# This file was generated by GoReleaser. DO NOT EDIT.
cask "praxis" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "ea8c74b677b15ee1731981350bd6630233d9323ae5fd01ed21e474fe0a83fa3f"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9c7268b49a153b07c316ba093b6ae4b3d896a0b011c8cfba4e0865e8bc7d982"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a589b84b8be437f5e72cc8b2e3dff7c532eb9898ee3aab2809bee0d4ab6b916"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8fd2eba47735569ff71fb277bdc35df9134b7f4d57bb35413d2c5275f4ca402c"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "praxis"
  desc "Autonomous AI bot swarm orchestrator"
  homepage "https://github.com/martinsuchenak/praxis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "praxis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/praxis"]
    end
  end

  # No zap stanza required

end
