# This file was generated by GoReleaser. DO NOT EDIT.
cask "praxis" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "97d11bf6877180394c021b6246ab47db2ba6494cab8b5f43d686cc54c21a5119"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6a45cda0af4631327f97b26c08fb40b2ed5148ccab1092836b5ce30a60933052"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c5364ef0ac1826b923d062b4422eb4ed1923a71325a28f418a409e234f96c83"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "13ca9d5a23e72a9f195f10b40d4d341702966a06d26356896e3e98ef9f599a5e"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_linux_amd64.tar.gz"
    end
  end

  name "praxis"
  desc "Autonomous AI bot swarm orchestrator"
  homepage "https://github.com/martinsuchenak/praxis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "praxis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/praxis"]
    end
  end

  # No zap stanza required
end
