# This file was generated by GoReleaser. DO NOT EDIT.
cask "praxis" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "d8af7e9c8ac19670968bcb966be88ae16a114b059ce9426ca17e9cc4fe684ecf"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fccce444c86a4efbf9add638ad00c894f24a2c55963e69ec0745d7c707f15354"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a33ab29c3dee28c014e296205ec2ec3874bb5d29f2e321ad93550112573fc75"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df5fe09cb6f479486b6977db6e2dc706b50d5ae713ccd86d69dcb7f89d66d4eb"
      url "https://github.com/martinsuchenak/praxis/releases/download/v#{version}/praxis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "praxis"
  desc "Autonomous AI bot swarm orchestrator"
  homepage "https://github.com/martinsuchenak/praxis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "praxis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/praxis"]
    end
  end

  # No zap stanza required

end
