# This file was generated by GoReleaser. DO NOT EDIT.
cask "rackd" do
  name "rackd"
  desc "Device inventory and IPAM management"
  homepage "https://github.com/martinsuchenak/rackd"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rackd"

  on_macos do
    on_intel do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_darwin_amd64.tar.gz"
      sha256 "553856633f484e99b2b8b9cdf85c7e491c9525b4f38319827506fe22fb9d885e"
    end
    on_arm do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_darwin_arm64.tar.gz"
      sha256 "bcff77a16ac6fd6ddb3175ccff1291f4fc7b5f4820d6b3b9bf11ec2b971c2807"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_linux_amd64.tar.gz"
      sha256 "e3a93d4857045e0c4d125d72182cd04f271146f60c533df05ccfc3159c734bf4"
    end
    on_arm do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_linux_arm64.tar.gz"
      sha256 "8d29a357a140eaa6ac37d68d987e04bfbf48078182825607a656ae1e7fa99f03"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rackd"]
    end
  end

  # No zap stanza required
end
