# This file was generated by GoReleaser. DO NOT EDIT.
cask "rackd" do
  version "0.0.15"

  on_macos do
    on_intel do
      sha256 "2c27ce8c1f53be7e4d26cb353914fbbae3378ade0ffe2e1b9cc4abadede8f082"
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d15ac1d7e5c1c5ee1de06f009af16eb465d321359f2a1898a725578471ac795"
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13c399b1c957f38205158128532f5d92bcc89f0be417f0189dd6cfe1f49bb808"
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "beae0826d949c5b2492f94731f454db43d418b0115e3772ec416576f522d1c75"
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rackd"
  desc "Device inventory and IPAM management"
  homepage "https://github.com/martinsuchenak/rackd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rackd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rackd"]
    end
  end

  # No zap stanza required

end
