# This file was generated by GoReleaser. DO NOT EDIT.
cask "rackd" do
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_darwin_amd64.tar.gz"
      sha256 "1370ecc3f114e584b18c1a0709796ad9fd611249493d7f200bf73d6cacbdd422"
    end
    on_arm do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_darwin_arm64.tar.gz"
      sha256 "29aa8f672e9f46db946cf026fc6a1497f13080d5f382af30173ae2e47f2f7b7e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_linux_amd64.tar.gz"
      sha256 "6b54fee8daf38abd1f091947de426c35a6fb1c81b81ca7761a9863b2edd1f9e4"
    end
    on_arm do
      url "https://github.com/martinsuchenak/rackd/releases/download/v#{version}/rackd_#{version}_linux_arm64.tar.gz"
      sha256 "c31d75e4dfb061b7b60a2c9eb6e912cbc23ed1262c36317c3b2baeaa5efa7b7a"
    end
  end

  name "rackd"
  desc "Device inventory and IPAM management"
  homepage "https://github.com/martinsuchenak/rackd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rackd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rackd"]
    end
  end

  # No zap stanza required

end
