# This file was generated by GoReleaser. DO NOT EDIT.
cask "skopos" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "47c7705eb4b0bbe33c1b9009ba9cfb26f4fd43261669333c474eb18b2e7c2ffe"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5bf00869be7c105f49f1115cdddbc39cfe44f74487a5ff554f25585302e8fe97"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "de6ca1ab956e1ab26545bec9a5353b99c58af6d3b08e1fd3c7a470ec73fa0a49"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "10f91db4e1a3e114fd0f596566eecc5d06ccd40a3c98169553e15a82e6e5abb9"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skopos"
  desc "AI agent coordination dashboard — shared memory, plans, and real-time status"
  homepage "https://github.com/martinsuchenak/skopos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skopos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skopos"]
    end
  end

  # No zap stanza required
end
