# This file was generated by GoReleaser. DO NOT EDIT.
cask "skopos" do
  version "0.0.11"

  on_macos do
    on_arm do
      sha256 "6edb23ffd239fd76a1078dc2caf199bc8204cac2979c641fb184efa61ef797b8"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1f836ff6400ade0e2a47d89aa5ee1acddd4c0c7b283bf9b1a17cda0993830d8"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "832943a83390d122571b9451c9cabe138bc343bcd49c3dad72fad3df64e3b5c3"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af04ecc42d3b31f289da47d70415aec0ccd12c529ad14253e96ce11c55827980"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skopos"
  desc "AI agent coordination dashboard — shared memory, plans, and real-time status"
  homepage "https://github.com/martinsuchenak/skopos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skopos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skopos"]
    end
  end

  # No zap stanza required
end
