# This file was generated by GoReleaser. DO NOT EDIT.
cask "skopos" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "4ff4a36f07735cdd8a33db9afbf96d52a426a901aa7ed3b6e9cea922e30ce42b"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d81d4b3eeac22e722e37afefa4bf57dbaafc93d8f41c241cf0cdfb3fba9d4f8a"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fc10c66f509e0c6fcd5e14ebcda3f66a6fdf44b878c0cdee76904d9e84f2ac3b"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4662e00527bcf22a89a506e76a4719c95f8b22a3a5f6abf63def0974017547d5"
      url "https://github.com/martinsuchenak/skopos/releases/download/v#{version}/skopos_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skopos"
  desc "AI agent coordination dashboard — shared memory, plans, and real-time status"
  homepage "https://github.com/martinsuchenak/skopos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skopos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skopos"]
    end
  end

  # No zap stanza required
end
