# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phantom < Formula
  desc "CLI tool for managing overlay filesystems for parallel AI agent development"
  homepage "https://github.com/martinsuchenak/phantom"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.2/phantom_0.0.2_darwin_amd64.tar.gz"
      sha256 "ffa62b817e6e00aff0828cdd25a7dfb04cfefe0d7aa0f1652d681687d3e13e45"

      def install
        bin.install "phantom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.2/phantom_0.0.2_darwin_arm64.tar.gz"
      sha256 "b1fda9dbe0135769169e2ff04dc17926c929d0dd1ba0661e7b3524d00442aad7"

      def install
        bin.install "phantom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.2/phantom_0.0.2_linux_amd64.tar.gz"
      sha256 "3612335660540ca214a82d90f86fda7d9151ea7ae61df8964a176fed19894555"
      def install
        bin.install "phantom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.2/phantom_0.0.2_linux_arm64.tar.gz"
      sha256 "95882e340ae897f86e1d88d861295f9d9be410e7004a7c644deaba2e5ba887cc"
      def install
        bin.install "phantom"
      end
    end
  end

  test do
    system "#{bin}/phantom", "--version"
  end
end
