# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phantom < Formula
  desc "CLI tool for managing overlay filesystems for parallel AI agent development"
  homepage "https://github.com/martinsuchenak/phantom"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.3/phantom_0.0.3_darwin_amd64.tar.gz"
      sha256 "4ab5d2aca1b0e101f7c5e4519c2215c3c99a323e624abe545885ed0f419b35a1"

      def install
        bin.install "phantom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.3/phantom_0.0.3_darwin_arm64.tar.gz"
      sha256 "fb43624f803d8cfb3f0b8e3f72197edff4b0dbf73da07f498f43705cf10dd67b"

      def install
        bin.install "phantom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.3/phantom_0.0.3_linux_amd64.tar.gz"
      sha256 "ee5417311cd73cd01a296709043d1dfe6955296c09139d9b6c1646bf36cea797"
      def install
        bin.install "phantom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinsuchenak/phantom/releases/download/v0.0.3/phantom_0.0.3_linux_arm64.tar.gz"
      sha256 "d7756c079731e8ba37ccf477d8ecfc381526dd0d36729c6fabcf5be482505be4"
      def install
        bin.install "phantom"
      end
    end
  end

  test do
    system "#{bin}/phantom", "--version"
  end
end
