# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rackd < Formula
  desc "Device inventory and IPAM management"
  homepage "https://github.com/martinsuchenak/rackd"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martinsuchenak/rackd/releases/download/v0.0.3/rackd_0.0.3_darwin_amd64.tar.gz"
      sha256 "28a9b030833c68143e92705f73187344ab42afd310dc143ffeaae79c37194019"

      define_method(:install) do
        bin.install "rackd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martinsuchenak/rackd/releases/download/v0.0.3/rackd_0.0.3_darwin_arm64.tar.gz"
      sha256 "951e3dce9138c0f90c380baad270b37b2f9ff4a5c696677ed786f62becbf8a85"

      define_method(:install) do
        bin.install "rackd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinsuchenak/rackd/releases/download/v0.0.3/rackd_0.0.3_linux_amd64.tar.gz"
      sha256 "b38c0a1b28f19e1569f709b5ce3cbb374b40db4bd177c138b14d74a04eada26b"
      define_method(:install) do
        bin.install "rackd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinsuchenak/rackd/releases/download/v0.0.3/rackd_0.0.3_linux_arm64.tar.gz"
      sha256 "aa078b3cc3695b6ff4bf00c4af99a1543846f304378bd6f1a746c4af0eab76ad"
      define_method(:install) do
        bin.install "rackd"
      end
    end
  end

  test do
    system "#{bin}/rackd", "--version"
  end
end
